"""
data/schema.py
Pydantic models for BistroBrain data structures.
"""
from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


# ─────────────────────────────────────────────
# Enums
# ─────────────────────────────────────────────

class CategoryEnum(str, Enum):
    FOOD = "food"
    BEVERAGE = "beverage"
    DESSERT = "dessert"
    MISC = "misc"


class ActionPriority(str, Enum):
    URGENT = "urgent"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class ActionType(str, Enum):
    INVENTORY = "inventory"
    MARKETING = "marketing"
    PRICING = "pricing"
    STAFFING = "staffing"
    INSIGHT = "insight"


# ─────────────────────────────────────────────
# POS Transaction Models
# ─────────────────────────────────────────────

class POSTransaction(BaseModel):
    """Raw POS transaction record."""
    transaction_id: str
    timestamp: datetime
    item_name: str
    category: CategoryEnum
    quantity: float
    unit_price: float
    food_cost: float                          # Cost to restaurant
    table_id: Optional[str] = None
    server_id: Optional[str] = None
    payment_method: Optional[str] = None

    @property
    def revenue(self) -> float:
        return self.quantity * self.unit_price

    @property
    def gross_profit(self) -> float:
        return self.revenue - (self.quantity * self.food_cost)

    @property
    def margin(self) -> float:
        return self.gross_profit / self.revenue if self.revenue else 0.0


class DailySummary(BaseModel):
    """Aggregated daily POS summary."""
    date: date
    total_revenue: float
    total_food_cost: float
    gross_profit: float
    avg_margin: float
    cover_count: int                          # Number of customers served
    top_items: list[str] = Field(default_factory=list)
    low_margin_items: list[str] = Field(default_factory=list)


# ─────────────────────────────────────────────
# Inventory Models
# ─────────────────────────────────────────────

class InventoryItem(BaseModel):
    """Current inventory record."""
    item_id: str
    item_name: str
    category: CategoryEnum
    quantity_kg: float
    unit_cost: float
    expiry_date: Optional[date] = None
    reorder_level_kg: float = 2.0
    supplier: Optional[str] = None

    @property
    def is_low_stock(self) -> bool:
        return self.quantity_kg <= self.reorder_level_kg

    @property
    def days_until_expiry(self) -> Optional[int]:
        if self.expiry_date is None:
            return None
        return (self.expiry_date - date.today()).days


class InventoryAlert(BaseModel):
    """Alert generated by InventoryAgent."""
    item: InventoryItem
    alert_type: str                           # "expiry" | "low_stock"
    urgency_hours: Optional[int] = None
    suggested_action: str


# ─────────────────────────────────────────────
# Action Card Model
# ─────────────────────────────────────────────

class ActionCard(BaseModel):
    """A single actionable recommendation card."""
    card_id: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    priority: ActionPriority
    action_type: ActionType
    headline: str                             # Short title
    body: str                                 # Full explanation
    action_steps: list[str] = Field(default_factory=list)
    social_copy: Optional[str] = None        # Ready-to-post marketing text
    expected_impact: Optional[str] = None    # e.g. "Recover ₹2,400 in waste"

    def to_whatsapp_message(self) -> str:
        """Format card for WhatsApp delivery."""
        priority_emoji = {
            ActionPriority.URGENT: "🔴",
            ActionPriority.HIGH: "🟠",
            ActionPriority.MEDIUM: "🟡",
            ActionPriority.LOW: "🟢",
        }[self.priority]

        lines = [
            f"{priority_emoji} *{self.priority.upper()} — {self.action_type.title()}*",
            f"*{self.headline}*",
            "",
            self.body,
        ]

        if self.action_steps:
            lines.append("\n*Steps:*")
            for i, step in enumerate(self.action_steps, 1):
                lines.append(f"  {i}. {step}")

        if self.social_copy:
            lines.append(f"\n📱 *Post-ready caption:*\n_{self.social_copy}_")

        if self.expected_impact:
            lines.append(f"\n💡 *Impact:* {self.expected_impact}")

        return "\n".join(lines)


# ─────────────────────────────────────────────
# API Request / Response Models
# ─────────────────────────────────────────────

class QueryRequest(BaseModel):
    """Natural language query from restaurant owner."""
    question: str = Field(..., min_length=3, max_length=500)
    date_context: Optional[date] = None      # Optional: focus on specific date

    @field_validator("question")
    @classmethod
    def strip_question(cls, v: str) -> str:
        return v.strip()


class QueryResponse(BaseModel):
    """LLM answer with supporting evidence."""
    question: str
    answer: str
    confidence: float = Field(ge=0.0, le=1.0)
    sources: list[str] = Field(default_factory=list)
    follow_up_suggestions: list[str] = Field(default_factory=list)


class DailyDigestResponse(BaseModel):
    """Full daily digest payload."""
    date: date
    restaurant_name: str
    summary: DailySummary
    action_cards: list[ActionCard]
    whatsapp_sent: bool = False
